import {
  PerformanceReview,
  Employee,
  TrainingRecommendation,
  PromotionRecommendation,
  PerformanceSummary,
  TopPerformer,
  EmployeeNeedingImprovement,
  KPI,
} from '@/types/performance'

export const mockEmployees: Employee[] = [
  { id: 'EMP001', name: 'John Doe', department: 'IT', position: 'Senior Developer', email: 'john.doe@example.com' },
  { id: 'EMP002', name: 'Jane Smith', department: 'HR', position: 'HR Manager', email: 'jane.smith@example.com' },
  { id: 'EMP003', name: 'Michael Chen', department: 'Finance', position: 'Financial Analyst', email: 'michael.chen@example.com' },
  { id: 'EMP004', name: 'Emily Davis', department: 'Marketing', position: 'Marketing Specialist', email: 'emily.davis@example.com' },
  { id: 'EMP005', name: 'Robert Brown', department: 'IT', position: 'Software Engineer', email: 'robert.brown@example.com' },
  { id: 'EMP006', name: 'Sarah Williams', department: 'Operations', position: 'Operations Manager', email: 'sarah.williams@example.com' },
  { id: 'EMP007', name: 'David Wilson', department: 'Sales', position: 'Sales Representative', email: 'david.wilson@example.com' },
  { id: 'EMP008', name: 'Lisa Anderson', department: 'HR', position: 'Recruiter', email: 'lisa.anderson@example.com' },
]

export const mockReviewers: Employee[] = [
  { id: 'REV001', name: 'Alice Johnson', department: 'Management', position: 'Director', email: 'alice.johnson@example.com' },
  { id: 'REV002', name: 'Tom Martinez', department: 'Management', position: 'VP Operations', email: 'tom.martinez@example.com' },
  { id: 'REV003', name: 'Patricia Lee', department: 'Management', position: 'Senior Manager', email: 'patricia.lee@example.com' },
]

export const mockPerformanceSummary: PerformanceSummary = {
  averageKpiScore: 87.5,
  employeesUpForPromotion: 12,
  employeesNeedingTraining: 8,
  totalReviewsThisQuarter: 45,
}

export const mockTopPerformers: TopPerformer[] = [
  {
    id: '1',
    employeeName: 'John Doe',
    department: 'IT',
    position: 'Senior Developer',
    totalScore: 95.5,
    kpiScore: 98,
    behaviorScore: 94,
    attendanceScore: 94.5,
  },
  {
    id: '2',
    employeeName: 'Jane Smith',
    department: 'HR',
    position: 'HR Manager',
    totalScore: 94.2,
    kpiScore: 96,
    behaviorScore: 93,
    attendanceScore: 93.5,
  },
  {
    id: '3',
    employeeName: 'Michael Chen',
    department: 'Finance',
    position: 'Financial Analyst',
    totalScore: 92.8,
    kpiScore: 94,
    behaviorScore: 92,
    attendanceScore: 92.5,
  },
  {
    id: '4',
    employeeName: 'Emily Davis',
    department: 'Marketing',
    position: 'Marketing Specialist',
    totalScore: 91.5,
    kpiScore: 93,
    behaviorScore: 91,
    attendanceScore: 90.5,
  },
  {
    id: '5',
    employeeName: 'Robert Brown',
    department: 'IT',
    position: 'Software Engineer',
    totalScore: 90.2,
    kpiScore: 92,
    behaviorScore: 90,
    attendanceScore: 88.5,
  },
]

export const mockEmployeesNeedingImprovement: EmployeeNeedingImprovement[] = [
  {
    id: '1',
    employeeName: 'David Wilson',
    department: 'Sales',
    position: 'Sales Representative',
    totalScore: 65.5,
    kpiScore: 60,
    behaviorScore: 70,
    attendanceScore: 66.5,
    improvementAreas: ['KPI Performance', 'Attendance'],
  },
  {
    id: '2',
    employeeName: 'Lisa Anderson',
    department: 'HR',
    position: 'Recruiter',
    totalScore: 68.2,
    kpiScore: 65,
    behaviorScore: 72,
    attendanceScore: 67.5,
    improvementAreas: ['KPI Performance', 'Time Management'],
  },
  {
    id: '3',
    employeeName: 'Mark Thompson',
    department: 'Operations',
    position: 'Operations Assistant',
    totalScore: 70.8,
    kpiScore: 68,
    behaviorScore: 75,
    attendanceScore: 69.5,
    improvementAreas: ['KPI Performance'],
  },
]

export const mockPerformanceReviews: PerformanceReview[] = [
  {
    id: 'REV001',
    employeeId: 'EMP001',
    employeeName: 'John Doe',
    reviewerId: 'REV001',
    reviewerName: 'Alice Johnson',
    period: 'Q1 2024',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    kpiScore: 98,
    behaviorScore: 94,
    attendanceScore: 94.5,
    totalScore: 95.5,
    status: 'completed',
    remarks: 'Excellent performance throughout the quarter. Consistently exceeded expectations.',
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-04-05T14:30:00Z',
  },
  {
    id: 'REV002',
    employeeId: 'EMP002',
    employeeName: 'Jane Smith',
    reviewerId: 'REV002',
    reviewerName: 'Tom Martinez',
    period: 'Q1 2024',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    kpiScore: 96,
    behaviorScore: 93,
    attendanceScore: 93.5,
    totalScore: 94.2,
    status: 'approved',
    remarks: 'Strong leadership and team management skills. Great work on the HR initiatives.',
    createdAt: '2024-04-02T09:00:00Z',
    updatedAt: '2024-04-06T11:00:00Z',
  },
  {
    id: 'REV003',
    employeeId: 'EMP003',
    employeeName: 'Michael Chen',
    reviewerId: 'REV001',
    reviewerName: 'Alice Johnson',
    period: 'Q1 2024',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    kpiScore: 94,
    behaviorScore: 92,
    attendanceScore: 92.5,
    totalScore: 92.8,
    status: 'pending',
    remarks: 'Good analytical skills. Continue to improve communication with stakeholders.',
    createdAt: '2024-04-03T11:00:00Z',
    updatedAt: '2024-04-03T11:00:00Z',
  },
  {
    id: 'REV004',
    employeeId: 'EMP004',
    employeeName: 'Emily Davis',
    reviewerId: 'REV003',
    reviewerName: 'Patricia Lee',
    period: 'Q1 2024',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    kpiScore: 93,
    behaviorScore: 91,
    attendanceScore: 90.5,
    totalScore: 91.5,
    status: 'draft',
    remarks: 'Creative marketing campaigns. Working on improving project timelines.',
    createdAt: '2024-04-04T10:30:00Z',
    updatedAt: '2024-04-04T10:30:00Z',
  },
  {
    id: 'REV005',
    employeeId: 'EMP005',
    employeeName: 'Robert Brown',
    reviewerId: 'REV001',
    reviewerName: 'Alice Johnson',
    period: 'Q1 2024',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    kpiScore: 92,
    behaviorScore: 90,
    attendanceScore: 88.5,
    totalScore: 90.2,
    status: 'completed',
    remarks: 'Solid technical skills. Focus on improving attendance.',
    createdAt: '2024-04-05T09:15:00Z',
    updatedAt: '2024-04-07T16:00:00Z',
  },
  {
    id: 'REV006',
    employeeId: 'EMP006',
    employeeName: 'Sarah Williams',
    reviewerId: 'REV002',
    reviewerName: 'Tom Martinez',
    period: 'Q1 2024',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    kpiScore: 88,
    behaviorScore: 90,
    attendanceScore: 89.5,
    totalScore: 89.2,
    status: 'completed',
    remarks: 'Good operational management. Continue to streamline processes.',
    createdAt: '2024-04-06T08:00:00Z',
    updatedAt: '2024-04-08T12:00:00Z',
  },
]

export const mockTrainingRecommendations: TrainingRecommendation[] = [
  {
    id: 'TR001',
    employeeId: 'EMP001',
    employeeName: 'David Wilson',
    department: 'Sales',
    position: 'Sales Representative',
    recommendedTraining: 'Advanced Sales Techniques',
    priority: 'high',
    reason: 'Low KPI scores in sales performance',
    estimatedDuration: '2 weeks',
  },
  {
    id: 'TR002',
    employeeId: 'EMP002',
    employeeName: 'Lisa Anderson',
    department: 'HR',
    position: 'Recruiter',
    recommendedTraining: 'Time Management & Productivity',
    priority: 'high',
    reason: 'Needs improvement in time management and KPI performance',
    estimatedDuration: '1 week',
  },
  {
    id: 'TR003',
    employeeId: 'EMP003',
    employeeName: 'Mark Thompson',
    department: 'Operations',
    position: 'Operations Assistant',
    recommendedTraining: 'Performance Optimization',
    priority: 'medium',
    reason: 'KPI performance below target',
    estimatedDuration: '1 week',
  },
  {
    id: 'TR004',
    employeeId: 'EMP004',
    employeeName: 'James Taylor',
    department: 'IT',
    position: 'Junior Developer',
    recommendedTraining: 'Advanced Programming Skills',
    priority: 'medium',
    reason: 'Skill development for career growth',
    estimatedDuration: '3 weeks',
  },
  {
    id: 'TR005',
    employeeId: 'EMP005',
    employeeName: 'Maria Garcia',
    department: 'Finance',
    position: 'Accountant',
    recommendedTraining: 'Financial Analysis & Reporting',
    priority: 'low',
    reason: 'Enhancement of existing skills',
    estimatedDuration: '2 weeks',
  },
]

export const mockPromotionRecommendations: PromotionRecommendation[] = [
  {
    id: 'PR001',
    employeeId: 'EMP001',
    employeeName: 'John Doe',
    department: 'IT',
    currentPosition: 'Senior Developer',
    currentSalaryGrade: 'SG-18',
    proposedPosition: 'Lead Developer',
    proposedSalaryGrade: 'SG-20',
    promotionReason: 'Consistently exceeds expectations, strong leadership potential',
    performanceScore: 95.5,
    yearsInPosition: 3,
  },
  {
    id: 'PR002',
    employeeId: 'EMP002',
    employeeName: 'Jane Smith',
    department: 'HR',
    currentPosition: 'HR Manager',
    currentSalaryGrade: 'SG-20',
    proposedPosition: 'Senior HR Manager',
    proposedSalaryGrade: 'SG-22',
    promotionReason: 'Excellent team management, successful HR initiatives',
    performanceScore: 94.2,
    yearsInPosition: 4,
  },
  {
    id: 'PR003',
    employeeId: 'EMP003',
    employeeName: 'Michael Chen',
    department: 'Finance',
    currentPosition: 'Financial Analyst',
    currentSalaryGrade: 'SG-16',
    proposedPosition: 'Senior Financial Analyst',
    proposedSalaryGrade: 'SG-18',
    promotionReason: 'Strong analytical skills, valuable contributions to financial planning',
    performanceScore: 92.8,
    yearsInPosition: 2.5,
  },
  {
    id: 'PR004',
    employeeId: 'EMP004',
    employeeName: 'Emily Davis',
    department: 'Marketing',
    currentPosition: 'Marketing Specialist',
    currentSalaryGrade: 'SG-16',
    proposedPosition: 'Marketing Manager',
    proposedSalaryGrade: 'SG-18',
    promotionReason: 'Creative campaigns, good project management skills',
    performanceScore: 91.5,
    yearsInPosition: 3,
  },
]

export const mockKPIs: KPI[] = [
  {
    id: 'KPI001',
    name: 'KPI Score',
    description: 'Key Performance Indicators score based on job-specific metrics',
    category: 'kpi',
    weight: 40,
    maxScore: 100,
    minScore: 0,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'KPI002',
    name: 'Behavior Score',
    description: 'Assessment of professional behavior, teamwork, and communication',
    category: 'behavior',
    weight: 30,
    maxScore: 100,
    minScore: 0,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'KPI003',
    name: 'Attendance Score',
    description: 'Punctuality and attendance record',
    category: 'attendance',
    weight: 30,
    maxScore: 100,
    minScore: 0,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'KPI004',
    name: 'Quality of Work',
    description: 'Accuracy and quality of deliverables',
    category: 'kpi',
    weight: 25,
    maxScore: 100,
    minScore: 0,
    isActive: false,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'KPI005',
    name: 'Teaching Effectiveness',
    description: 'Assessment of teacher\'s ability to effectively teach and engage students',
    category: 'other',
    weight: 15,
    maxScore: 100,
    minScore: 0,
    isActive: true,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
]

