'use client';

import React, { useState, useEffect, useRef } from 'react';
import { X, Upload, FileText, AlertCircle } from 'lucide-react';
import { DisciplinaryRecord, SeverityLevel, DisciplinaryStatus, EvidenceFile } from '@/types/disciplinary';
import SeverityTag from './SeverityTag';
import StatusTag from './StatusTag';
import SearchableEmployeeSelect from './SearchableEmployeeSelect';

interface CaseViewModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (record: Partial<DisciplinaryRecord>) => Promise<void>;
  record?: DisciplinaryRecord | null;
  employees?: { id: string; name: string }[];
  supervisors?: { id: string; name: string }[];
  categories?: string[];
  violationTypes?: { id: string; name: string; category: string; defaultSeverity: SeverityLevel }[];
}

const CaseViewModal: React.FC<CaseViewModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
  record,
  employees = [],
  supervisors = [],
  categories = [],
  violationTypes = [],
}) => {
  const [formData, setFormData] = useState<Partial<DisciplinaryRecord>>({
    dateTime: new Date().toISOString().slice(0, 16),
    category: '',
    violation: '',
    employee: '',
    employeeId: '',
    severity: 'Minor',
    status: 'Ongoing',
    evidence: [],
    resolution: '',
    resolutionDate: '',
    remarks: '',
    interviewNotes: '',
    hrRemarks: '',
    recommendedPenalty: '',
    digitalAcknowledgment: false,
    supervisor: '',
    supervisorId: '',
    offenseCount: 0,
  });

  const [uploadedFiles, setUploadedFiles] = useState<EvidenceFile[]>([]);
  const [fileObjects, setFileObjects] = useState<Map<string, File>>(new Map()); // Store actual File objects
  const [uploading, setUploading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [repeatViolationWarning, setRepeatViolationWarning] = useState(false);
  const [showReviewModal, setShowReviewModal] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const isEditMode = !!record;

  // Case number is auto-generated by backend, no need to set it here

  // Load record data when editing
  useEffect(() => {
    if (record) {
      setFormData({
        ...record,
        dateTime: record.dateTime ? new Date(record.dateTime).toISOString().slice(0, 16) : '',
        resolutionDate: record.resolutionDate ? new Date(record.resolutionDate).toISOString().slice(0, 10) : '',
      });
      setUploadedFiles(record.evidence || []);
      // Check for repeat violations
      if (record.offenseCount && record.offenseCount >= 3) {
        setRepeatViolationWarning(true);
      }
    } else {
      // Reset form for new record
      setFormData({
        dateTime: new Date().toISOString().slice(0, 16),
        category: '',
        violation: '',
        employee: '',
        employeeId: '',
        severity: 'Minor',
        status: 'Ongoing',
        evidence: [],
        resolution: '',
        resolutionDate: '',
        remarks: '',
        interviewNotes: '',
        hrRemarks: '',
        recommendedPenalty: '',
        digitalAcknowledgment: false,
        supervisor: '',
        supervisorId: '',
        offenseCount: 0,
      });
      setUploadedFiles([]);
      setFileObjects(new Map());
      setRepeatViolationWarning(false);
    }
  }, [record, isOpen]);

  // Auto-fill resolution date when status changes to Resolved
  useEffect(() => {
    if (formData.status === 'Resolved' && !formData.resolutionDate) {
      setFormData((prev) => ({
        ...prev,
        resolutionDate: new Date().toISOString().slice(0, 10),
      }));
    }
  }, [formData.status]);

  // Auto-suggest penalty when violation repeats 3 times
  useEffect(() => {
    if (formData.offenseCount && formData.offenseCount >= 3 && !formData.recommendedPenalty) {
      setFormData((prev) => ({
        ...prev,
        recommendedPenalty: 'Escalation to HR Management - Consider suspension or termination review',
      }));
      setRepeatViolationWarning(true);
    }
  }, [formData.offenseCount]);

  // Auto-set severity when violation type changes
  const handleViolationChange = (violationName: string) => {
    const violation = violationTypes.find((v) => v.name === violationName);
    if (violation) {
      setFormData((prev) => ({
        ...prev,
        violation: violationName,
        category: violation.category,
        severity: violation.defaultSeverity,
      }));
    } else {
      setFormData((prev) => ({
        ...prev,
        violation: violationName,
      }));
    }
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;

    setUploading(true);
    const newFiles: EvidenceFile[] = [];
    const newFileObjects = new Map(fileObjects);

    for (const file of Array.from(files)) {
      // Create a preview URL for images
      const fileType = file.type.startsWith('image/')
        ? 'image'
        : file.type === 'application/pdf'
        ? 'pdf'
        : 'file';

      const fileId = `file-${Date.now()}-${Math.random()}`;
      const fileObj: EvidenceFile = {
        id: fileId,
        fileName: file.name,
        fileType,
        url: URL.createObjectURL(file), // Blob URL for preview
        uploadedAt: new Date().toISOString(),
      };

      newFiles.push(fileObj);
      // Store the actual File object for later upload
      newFileObjects.set(fileId, file);
    }

    setUploadedFiles((prev) => [...prev, ...newFiles]);
    setFileObjects(newFileObjects);
    setFormData((prev) => ({
      ...prev,
      evidence: [...uploadedFiles, ...newFiles],
    }));
    setUploading(false);

    // Reset file input
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleRemoveFile = (fileId: string) => {
    const updatedFiles = uploadedFiles.filter((f) => f.id !== fileId);
    const updatedFileObjects = new Map(fileObjects);
    updatedFileObjects.delete(fileId);
    
    // Revoke blob URL to free memory
    const fileToRemove = uploadedFiles.find(f => f.id === fileId);
    if (fileToRemove?.url && fileToRemove.url.startsWith('blob:')) {
      URL.revokeObjectURL(fileToRemove.url);
    }
    
    setUploadedFiles(updatedFiles);
    setFileObjects(updatedFileObjects);
    setFormData((prev) => ({
      ...prev,
      evidence: updatedFiles,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrors({});

    // Validation
    const newErrors: Record<string, string> = {};
    if (!formData.employee || !formData.employeeId) {
      newErrors.employee = 'Employee is required';
    }
    if (!formData.category) {
      newErrors.category = 'Category is required';
    }
    if (!formData.violation) {
      newErrors.violation = 'Violation type is required';
    }
    if (!formData.dateTime) {
      newErrors.dateTime = 'Date and time is required';
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // For new records, show review modal first
    if (!isEditMode) {
      setShowReviewModal(true);
      return;
    }

    // For edits, submit directly
    await submitForm();
  };

  const submitForm = async () => {
    setIsSubmitting(true);
    try {
      // Pass both evidence files and file objects to the parent
      await onSubmit({
        ...formData,
        evidence: uploadedFiles,
        _fileObjects: fileObjects, // Pass file objects separately for upload
      } as Partial<DisciplinaryRecord> & { _fileObjects?: Map<string, File> });
      setShowReviewModal(false);
      onClose();
    } catch (error) {
      console.error('Error submitting form:', error);
      setErrors({ submit: 'Failed to submit. Please try again.' });
      setShowReviewModal(false);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  // Get filtered violation types based on selected category
  const filteredViolations = formData.category
    ? violationTypes.filter((v) => v.category === formData.category)
    : violationTypes;

  // Get employee and supervisor names for review
  const employeeName = employees.find(emp => emp.id === formData.employeeId)?.name || formData.employee || 'N/A';
  const supervisorName = supervisors.find(sup => sup.id === formData.supervisorId)?.name || formData.supervisor || 'N/A';

  return (
    <>
      {/* Review Modal */}
      {showReviewModal && (
        <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-[60]">
          <div className="bg-white rounded-lg w-full max-w-3xl mx-4 max-h-[90vh] overflow-y-auto">
            <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
              <h3 className="text-xl font-bold text-gray-900">Review Case Information</h3>
              <button
                onClick={() => setShowReviewModal(false)}
                className="text-gray-400 hover:text-gray-600 transition-colors"
              >
                <X className="w-6 h-6" />
              </button>
            </div>
            
            <div className="p-6 space-y-6">
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="text-sm text-blue-800">
                  <strong>Please review all information before submitting.</strong> Once submitted, the case will be created and cannot be undone.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Employee Information */}
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Employee</h4>
                  <p className="text-gray-900">{employeeName}</p>
                </div>

                {/* Supervisor */}
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Supervisor</h4>
                  <p className="text-gray-900">{supervisorName}</p>
                </div>

                {/* Date & Time */}
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Date & Time</h4>
                  <p className="text-gray-900">
                    {formData.dateTime ? new Date(formData.dateTime).toLocaleString() : 'N/A'}
                  </p>
                </div>

                {/* Category */}
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Category</h4>
                  <p className="text-gray-900">{formData.category || 'N/A'}</p>
                </div>

                {/* Violation */}
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Violation Type</h4>
                  <p className="text-gray-900">{formData.violation || 'N/A'}</p>
                </div>

                {/* Severity */}
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Severity</h4>
                  <div className="mt-1">
                    <SeverityTag severity={formData.severity || 'Minor'} />
                  </div>
                </div>

                {/* Status */}
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Status</h4>
                  <div className="mt-1">
                    <StatusTag status={formData.status || 'Ongoing'} />
                  </div>
                </div>

                {/* Offense Count */}
                {formData.offenseCount && formData.offenseCount > 0 && (
                  <div>
                    <h4 className="text-sm font-semibold text-gray-700 mb-2">Offense Count</h4>
                    <p className="text-gray-900">{formData.offenseCount}</p>
                  </div>
                )}
              </div>

              {/* Remarks */}
              {formData.remarks && (
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Remarks</h4>
                  <p className="text-gray-900 whitespace-pre-wrap">{formData.remarks}</p>
                </div>
              )}

              {/* Interview Notes */}
              {formData.interviewNotes && (
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Interview Notes</h4>
                  <p className="text-gray-900 whitespace-pre-wrap">{formData.interviewNotes}</p>
                </div>
              )}

              {/* HR Remarks */}
              {formData.hrRemarks && (
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">HR Remarks</h4>
                  <p className="text-gray-900 whitespace-pre-wrap">{formData.hrRemarks}</p>
                </div>
              )}

              {/* Recommended Penalty */}
              {formData.recommendedPenalty && (
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Recommended Penalty</h4>
                  <p className="text-gray-900">{formData.recommendedPenalty}</p>
                </div>
              )}

              {/* Evidence Files */}
              {uploadedFiles.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Evidence Files</h4>
                  <div className="space-y-2">
                    {uploadedFiles.map((file) => (
                      <div key={file.id} className="flex items-center gap-2 text-sm text-gray-700">
                        <FileText className="w-4 h-4" />
                        <span>{file.fileName}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Resolution (if provided) */}
              {formData.resolution && (
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Resolution</h4>
                  <p className="text-gray-900 whitespace-pre-wrap">{formData.resolution}</p>
                </div>
              )}

              {/* Resolution Date */}
              {formData.resolutionDate && (
                <div>
                  <h4 className="text-sm font-semibold text-gray-700 mb-2">Resolution Date</h4>
                  <p className="text-gray-900">
                    {new Date(formData.resolutionDate).toLocaleDateString()}
                  </p>
                </div>
              )}
            </div>

            {/* Review Modal Actions */}
            <div className="sticky bottom-0 bg-gray-50 border-t border-gray-200 px-6 py-4 flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setShowReviewModal(false)}
                className="px-4 py-2 text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
                disabled={isSubmitting}
              >
                Back to Edit
              </button>
              <button
                type="button"
                onClick={submitForm}
                className="px-6 py-2 bg-[#800000] text-white rounded-lg hover:bg-[#600000] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={isSubmitting}
              >
                {isSubmitting ? 'Creating...' : 'Confirm & Create Case'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Main Form Modal */}
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 overflow-y-auto">
      <div
        className="bg-white rounded-lg w-full max-w-5xl mx-4 my-8 max-h-[95vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900">
            {isEditMode ? 'Edit Disciplinary Case' : 'Add Disciplinary Case'}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Repeat Violation Warning */}
        {repeatViolationWarning && (
          <div className="mx-6 mt-4 p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <h4 className="font-semibold text-red-900 mb-1">Repeat Violation Warning</h4>
              <p className="text-sm text-red-700">
                This employee has {formData.offenseCount || 0} previous violations. Please review the recommended
                penalty.
              </p>
            </div>
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6">
          <div className="space-y-6">
            {/* Date & Time */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Date & Time <span className="text-red-500">*</span>
              </label>
              <input
                type="datetime-local"
                value={formData.dateTime || ''}
                onChange={(e) => setFormData({ ...formData, dateTime: e.target.value })}
                className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent ${
                  errors.dateTime ? 'border-red-500' : 'border-gray-300'
                }`}
                required
              />
              {errors.dateTime && (
                <p className="mt-1 text-sm text-red-600">{errors.dateTime}</p>
              )}
            </div>

            {/* Employee and Supervisor */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Employee <span className="text-red-500">*</span>
                </label>
                <SearchableEmployeeSelect
                  employees={employees}
                  value={formData.employeeId || ''}
                  onChange={(employeeId, employeeName) => {
                    setFormData({
                      ...formData,
                      employeeId,
                      employee: employeeName,
                    });
                  }}
                  error={errors.employee}
                  required
                  placeholder="Search or select employee..."
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Supervisor</label>
                <select
                  value={formData.supervisorId || ''}
                  onChange={(e) => {
                    const selected = supervisors.find((sup) => sup.id === e.target.value);
                    setFormData({
                      ...formData,
                      supervisorId: e.target.value,
                      supervisor: selected?.name || '',
                    });
                  }}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                >
                  <option value="">Select Supervisor</option>
                  {supervisors.map((sup) => (
                    <option key={sup.id} value={sup.id}>
                      {sup.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Category and Violation */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Category <span className="text-red-500">*</span>
                </label>
                <select
                  value={formData.category || ''}
                  onChange={(e) => {
                    setFormData({
                      ...formData,
                      category: e.target.value,
                      violation: '', // Reset violation when category changes
                    });
                  }}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent ${
                    errors.category ? 'border-red-500' : 'border-gray-300'
                  }`}
                  required
                >
                  <option value="">Select Category</option>
                  {categories.map((cat) => (
                    <option key={cat} value={cat}>
                      {cat}
                    </option>
                  ))}
                </select>
                {errors.category && (
                  <p className="mt-1 text-sm text-red-600">{errors.category}</p>
                )}
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Violation Type <span className="text-red-500">*</span>
                </label>
                <select
                  value={formData.violation || ''}
                  onChange={(e) => handleViolationChange(e.target.value)}
                  disabled={!formData.category}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent ${
                    errors.violation ? 'border-red-500' : 'border-gray-300'
                  } ${!formData.category ? 'bg-gray-100 cursor-not-allowed' : ''}`}
                  required
                >
                  <option value="">Select Violation</option>
                  {filteredViolations.map((v) => (
                    <option key={v.id} value={v.name}>
                      {v.name}
                    </option>
                  ))}
                </select>
                {errors.violation && (
                  <p className="mt-1 text-sm text-red-600">{errors.violation}</p>
                )}
              </div>
            </div>

            {/* Severity and Status */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Severity Level
                </label>
                <div className="flex items-center gap-3">
                  <select
                    value={formData.severity || 'Minor'}
                    onChange={(e) =>
                      setFormData({ ...formData, severity: e.target.value as SeverityLevel })
                    }
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                  >
                    <option value="Minor">Minor</option>
                    <option value="Moderate">Moderate</option>
                    <option value="Major">Major</option>
                  </select>
                  <SeverityTag severity={(formData.severity as SeverityLevel) || 'Minor'} />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
                <div className="flex items-center gap-3">
                  <select
                    value={formData.status || 'Ongoing'}
                    onChange={(e) =>
                      setFormData({ ...formData, status: e.target.value as DisciplinaryStatus })
                    }
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                  >
                    <option value="Ongoing">Ongoing</option>
                    <option value="For Review">For Review</option>
                    <option value="Resolved">Resolved</option>
                    <option value="Closed">Closed</option>
                  </select>
                  <StatusTag status={(formData.status as DisciplinaryStatus) || 'Ongoing'} />
                </div>
              </div>
            </div>

            {/* Offense Count and Recommended Penalty */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Offense Count (Auto-calculated)
                </label>
                <input
                  type="number"
                  value={formData.offenseCount || 0}
                  onChange={(e) =>
                    setFormData({ ...formData, offenseCount: parseInt(e.target.value) || 0 })
                  }
                  className="w-full px-3 py-2 bg-gray-100 text-gray-600 border border-gray-300 rounded-lg cursor-not-allowed"
                  readOnly
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Recommended Penalty
                </label>
                <input
                  type="text"
                  value={formData.recommendedPenalty || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, recommendedPenalty: e.target.value })
                  }
                  placeholder="Auto-suggested based on repeat violations"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                />
              </div>
            </div>

            {/* Description of Incident */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Description of Incident <span className="text-red-500">*</span>
              </label>
              <textarea
                value={formData.remarks || ''}
                onChange={(e) => setFormData({ ...formData, remarks: e.target.value })}
                rows={4}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                placeholder="Provide detailed description of the incident..."
                required
              />
            </div>

            {/* Evidence Upload */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Evidence</label>
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-6">
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  accept="image/*,.pdf,.doc,.docx"
                  onChange={handleFileUpload}
                  className="hidden"
                  id="evidence-upload"
                />
                <label
                  htmlFor="evidence-upload"
                  className="flex flex-col items-center justify-center cursor-pointer"
                >
                  <Upload className="w-10 h-10 text-gray-400 mb-2" />
                  <span className="text-sm text-gray-600">
                    Click to upload or drag and drop
                  </span>
                  <span className="text-xs text-gray-500 mt-1">
                    Images, PDFs, and documents (Max 10MB per file)
                  </span>
                </label>
              </div>
              {uploading && (
                <p className="mt-2 text-sm text-blue-600">Uploading files...</p>
              )}
              {uploadedFiles.length > 0 && (
                <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-4">
                  {uploadedFiles.map((file) => (
                    <div
                      key={file.id}
                      className="relative border border-gray-300 rounded-lg p-2 bg-gray-50"
                    >
                      <div className="flex items-center gap-2 mb-2">
                        <FileText className="w-4 h-4 text-gray-500" />
                        <span className="text-xs text-gray-700 truncate flex-1">
                          {file.fileName}
                        </span>
                      </div>
                      {file.fileType === 'image' && (
                        <img
                          src={file.url}
                          alt={file.fileName}
                          className="w-full h-20 object-cover rounded"
                        />
                      )}
                      <button
                        type="button"
                        onClick={() => handleRemoveFile(file.id)}
                        className="absolute top-1 right-1 p-1 bg-red-500 text-white rounded-full hover:bg-red-600"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Interview Notes */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Interview Notes
              </label>
              <textarea
                value={formData.interviewNotes || ''}
                onChange={(e) => setFormData({ ...formData, interviewNotes: e.target.value })}
                rows={3}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                placeholder="Notes from interviews with the employee..."
              />
            </div>

            {/* HR Remarks */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">HR Remarks</label>
              <textarea
                value={formData.hrRemarks || ''}
                onChange={(e) => setFormData({ ...formData, hrRemarks: e.target.value })}
                rows={3}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                placeholder="HR department comments and observations..."
              />
            </div>

            {/* Resolution and Resolution Date */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Resolution</label>
                <textarea
                  value={formData.resolution || ''}
                  onChange={(e) => setFormData({ ...formData, resolution: e.target.value })}
                  rows={3}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                  placeholder="Final resolution or action taken..."
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Resolution Date
                </label>
                <input
                  type="date"
                  value={formData.resolutionDate || ''}
                  onChange={(e) => setFormData({ ...formData, resolutionDate: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#800000] focus:border-transparent"
                />
              </div>
            </div>

            {/* Digital Acknowledgment */}
            <div className="flex items-center gap-2">
              <input
                type="checkbox"
                id="digitalAck"
                checked={formData.digitalAcknowledgment || false}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    digitalAcknowledgment: e.target.checked,
                  })
                }
                className="w-4 h-4 text-[#800000] border-gray-300 rounded focus:ring-[#800000]"
              />
              <label htmlFor="digitalAck" className="text-sm font-medium text-gray-700">
                Digital Acknowledgment
              </label>
            </div>

            {errors.submit && (
              <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
                {errors.submit}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex justify-end gap-3 pt-6 mt-6 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2 text-gray-700 bg-gray-200 rounded-lg hover:bg-gray-300 transition-colors"
              disabled={isSubmitting}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-6 py-2 bg-[#800000] text-white rounded-lg hover:bg-[#600000] transition-colors disabled:opacity-50"
              disabled={isSubmitting}
            >
              {isSubmitting
                ? isEditMode
                  ? 'Updating...'
                  : 'Creating...'
                : isEditMode
                ? 'Update Case'
                : 'Create Case'}
            </button>
          </div>
        </form>
      </div>
    </div>
    </>
  );
};

export default CaseViewModal;

