import { DisciplinaryRecord, EmployeeDisciplinaryHistory } from '@/types/disciplinary';

// Mock data for disciplinary records
export const mockDisciplinaryRecords: DisciplinaryRecord[] = [
  {
    id: '1',
    caseNo: 'DA-2024-0001',
    dateTime: '2024-01-15T09:30:00',
    category: 'Attendance',
    violation: 'Late Arrival',
    employee: 'John Doe',
    employeeId: 'EMP001',
    severity: 'Minor',
    status: 'Resolved',
    resolution: 'Verbal warning issued. Employee committed to punctuality.',
    resolutionDate: '2024-01-16',
    remarks: 'Employee arrived 45 minutes late without prior notice.',
    interviewNotes: 'Employee cited traffic congestion. Advised to plan commute better.',
    hrRemarks: 'First offense. Monitor for next 30 days.',
    recommendedPenalty: 'Verbal warning',
    digitalAcknowledgment: true,
    acknowledgedAt: '2024-01-15T10:00:00',
    supervisor: 'Jane Smith',
    supervisorId: 'SUP001',
    offenseCount: 1,
    evidence: [
      {
        id: 'ev1',
        fileName: 'attendance-log.pdf',
        fileType: 'pdf',
        url: '/sample-evidence/attendance-log.pdf',
      },
    ],
    createdAt: '2024-01-15T09:30:00',
    updatedAt: '2024-01-16T14:00:00',
  },
  {
    id: '2',
    caseNo: 'DA-2024-0002',
    dateTime: '2024-02-20T14:15:00',
    category: 'Behavior',
    violation: 'Insubordination',
    employee: 'Alice Johnson',
    employeeId: 'EMP002',
    severity: 'Major',
    status: 'For_Review',
    resolution: '',
    remarks: 'Employee refused to comply with supervisor instructions during a meeting.',
    interviewNotes: 'Employee claims instructions were unclear. Meeting scheduled to clarify expectations.',
    hrRemarks: 'Case under review by HR management. Decision pending.',
    recommendedPenalty: 'Written warning or suspension pending review',
    digitalAcknowledgment: false,
    supervisor: 'Robert Brown',
    supervisorId: 'SUP002',
    offenseCount: 2,
    evidence: [
      {
        id: 'ev2',
        fileName: 'incident-report.png',
        fileType: 'image',
        url: '/sample-evidence/incident-report.png',
      },
      {
        id: 'ev3',
        fileName: 'meeting-notes.pdf',
        fileType: 'pdf',
        url: '/sample-evidence/meeting-notes.pdf',
      },
    ],
    createdAt: '2024-02-20T14:15:00',
    updatedAt: '2024-02-21T10:30:00',
  },
  {
    id: '3',
    caseNo: 'DA-2024-0003',
    dateTime: '2024-03-10T11:00:00',
    category: 'Performance',
    violation: 'Missed Deadline',
    employee: 'Michael Chen',
    employeeId: 'EMP003',
    severity: 'Moderate',
    status: 'Ongoing',
    resolution: '',
    remarks: 'Employee failed to submit required report by the deadline, affecting project timeline.',
    interviewNotes: 'Employee cited workload. Discussed time management strategies.',
    hrRemarks: 'Monitoring progress. Follow-up scheduled next week.',
    recommendedPenalty: 'Performance improvement plan',
    digitalAcknowledgment: true,
    acknowledgedAt: '2024-03-10T12:00:00',
    supervisor: 'Sarah Williams',
    supervisorId: 'SUP003',
    offenseCount: 1,
    evidence: [
      {
        id: 'ev4',
        fileName: 'deadline-notice.pdf',
        fileType: 'pdf',
        url: '/sample-evidence/deadline-notice.pdf',
      },
    ],
    createdAt: '2024-03-10T11:00:00',
    updatedAt: '2024-03-10T11:00:00',
  },
  {
    id: '4',
    caseNo: 'DA-2024-0004',
    dateTime: '2024-03-25T08:45:00',
    category: 'Attendance',
    violation: 'Absence Without Leave',
    employee: 'John Doe',
    employeeId: 'EMP001',
    severity: 'Moderate',
    status: 'Resolved',
    resolution: 'Written warning issued. Employee required to submit leave request in advance.',
    resolutionDate: '2024-03-26',
    remarks: 'Employee did not report to work and failed to notify supervisor.',
    interviewNotes: 'Employee claims emergency situation. Requested documentation of emergency.',
    hrRemarks: 'Second offense. Written warning on file.',
    recommendedPenalty: 'Written warning',
    digitalAcknowledgment: true,
    acknowledgedAt: '2024-03-25T10:00:00',
    supervisor: 'Jane Smith',
    supervisorId: 'SUP001',
    offenseCount: 2,
    evidence: [],
    createdAt: '2024-03-25T08:45:00',
    updatedAt: '2024-03-26T15:00:00',
  },
  {
    id: '5',
    caseNo: 'DA-2024-0005',
    dateTime: '2024-04-05T16:20:00',
    category: 'Behavior',
    violation: 'Inappropriate Conduct',
    employee: 'Emily Davis',
    employeeId: 'EMP004',
    severity: 'Major',
    status: 'Closed',
    resolution: 'Case closed after investigation. Employee issued final warning.',
    resolutionDate: '2024-04-10',
    remarks: 'Employee engaged in unprofessional behavior with colleagues.',
    interviewNotes: 'Multiple witnesses interviewed. Employee acknowledged behavior and apologized.',
    hrRemarks: 'Final warning issued. Any further incidents may result in termination.',
    recommendedPenalty: 'Final written warning',
    digitalAcknowledgment: true,
    acknowledgedAt: '2024-04-06T09:00:00',
    supervisor: 'Robert Brown',
    supervisorId: 'SUP002',
    offenseCount: 1,
    evidence: [
      {
        id: 'ev5',
        fileName: 'witness-statement.pdf',
        fileType: 'pdf',
        url: '/sample-evidence/witness-statement.pdf',
      },
    ],
    createdAt: '2024-04-05T16:20:00',
    updatedAt: '2024-04-10T11:00:00',
  },
];

// Mock employee disciplinary histories
export const mockEmployeeHistories: EmployeeDisciplinaryHistory[] = [
  {
    employeeId: 'EMP001',
    employeeName: 'John Doe',
    totalCases: 2,
    ongoingCount: 0,
    pendingCount: 0,
    resolvedCount: 2,
    lastUpdated: '2024-03-26T15:00:00',
    offenses: mockDisciplinaryRecords.filter((r) => r.employeeId === 'EMP001'),
  },
  {
    employeeId: 'EMP002',
    employeeName: 'Alice Johnson',
    totalCases: 1,
    ongoingCount: 0,
    pendingCount: 1,
    resolvedCount: 0,
    lastUpdated: '2024-02-21T10:30:00',
    offenses: mockDisciplinaryRecords.filter((r) => r.employeeId === 'EMP002'),
  },
  {
    employeeId: 'EMP003',
    employeeName: 'Michael Chen',
    totalCases: 1,
    ongoingCount: 1,
    pendingCount: 0,
    resolvedCount: 0,
    lastUpdated: '2024-03-10T11:00:00',
    offenses: mockDisciplinaryRecords.filter((r) => r.employeeId === 'EMP003'),
  },
  {
    employeeId: 'EMP004',
    employeeName: 'Emily Davis',
    totalCases: 1,
    ongoingCount: 0,
    pendingCount: 0,
    resolvedCount: 1,
    lastUpdated: '2024-04-10T11:00:00',
    offenses: mockDisciplinaryRecords.filter((r) => r.employeeId === 'EMP004'),
  },
];

// Utility function to generate case number
export const generateCaseNumber = (): string => {
  const year = new Date().getFullYear();
  const randomNum = Math.floor(Math.random() * 10000)
    .toString()
    .padStart(4, '0');
  return `DA-${year}-${randomNum}`;
};

// Categories and violation types
export const categories = [
  'Attendance',
  'Behavior',
  'Performance',
  'Safety',
  'Policy Violation',
  'Other',
];

export const violationTypes = [
  { id: 'v1', name: 'Late Arrival', category: 'Attendance', defaultSeverity: 'Minor' as const },
  { id: 'v2', name: 'Absence Without Leave', category: 'Attendance', defaultSeverity: 'Moderate' as const },
  { id: 'v3', name: 'Excessive Absences', category: 'Attendance', defaultSeverity: 'Major' as const },
  { id: 'v4', name: 'Insubordination', category: 'Behavior', defaultSeverity: 'Major' as const },
  { id: 'v5', name: 'Inappropriate Conduct', category: 'Behavior', defaultSeverity: 'Major' as const },
  { id: 'v6', name: 'Workplace Harassment', category: 'Behavior', defaultSeverity: 'Major' as const },
  { id: 'v7', name: 'Missed Deadline', category: 'Performance', defaultSeverity: 'Moderate' as const },
  { id: 'v8', name: 'Poor Performance', category: 'Performance', defaultSeverity: 'Moderate' as const },
  { id: 'v9', name: 'Safety Violation', category: 'Safety', defaultSeverity: 'Major' as const },
  { id: 'v10', name: 'Policy Violation', category: 'Policy Violation', defaultSeverity: 'Moderate' as const },
];

